### ISSUE TITLE
Hide duplicate week

### ISSUE THREAD

**Issue by getaaron** [min/MNCalendarView#2]
Is there any way to hide the week of duplicate day cells between each month?  This would match the iOS calendar app.

![MNCalendarView screenshot](https://f.cloud.github.com/assets/789577/1104326/1ced4722-18f3-11e3-995f-e7ea1ad30e07.png)
![iOS Calendar App screenshot](https://f.cloud.github.com/assets/789577/1104333/848d8072-18f3-11e3-8222-0ea494866e5c.png)

**Comment by getaaron** [comment]
Also, the screenshot on the main page of this app doesn't do this, so maybe it's a bug?

**Comment by getaaron** [comment]
Looks like the issue is in `[MNCalendarView -collectionView: cellForItemAtIndexPath:]`.  The cell is set up using `[MNCalendarViewDayCell - setDate: month: calendar:]`, which should disable it if it's in the wrong month.

But the line after that:

```
[cell setEnabled:[self dateEnabled:date]];
```

overrides this logic.  (It ignores the cell's current `enabled` value.)

I was able to resolve it using:

```
if (cell.enabled)
    [cell setEnabled:[self dateEnabled:date]];
```

But this isn't a very clean solution.

**Comment by min** [comment]
Thanks, this should be fixed in an up coming release.
